services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
      - "443:8080"
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb+srv://lawpaddiapp:RwVvFWnZD1SzFL8G@cluster0.zejix6y.mongodb.net